# Search and Filter DataFrames in PySpark HW

Now it's time to put what you've learn into action with a homework assignment!

In case you need it again, here is the link to the documentation for the full list available function in pyspark.sql.functions library:
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql.html#functions


### First set up your Spark Session!
Alright so first things first, let's start up our pyspark instance.

In [1]:
import findspark
findspark.init()

import pyspark
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName("SF").getOrCreate()

In [3]:
spark

In [4]:
cores = spark._jsc.sc().getExecutorMemoryStatus().keySet().size()
print("you are working with",cores,"core(s)")

you are working with 1 core(s)

## Read in the DataFrame for this Notebook

We will be continuing to use the fifa19.csv file for this notebook. Make sure that you are writting the correct path to the file.

In [5]:
path = "../data/"

fifa = spark.read.csv(path+"fifa19.csv",header=True,inferSchema=True)

## About this dataframe

The **fifa19.csv** dataset includes a list of all the FIFA 2019 players and their attributes listed below: 

 - **General**: Age, Nationality, Overall, Potential, Club
 - **Metrics:** Value, Wage
 - **Player Descriptive:** Preferred Foot, International Reputation, Weak Foot, Skill Moves, Work Rate, Position, Jersey Number, Joined, Loaned From, Contract Valid Until, Height, Weight
 - **Possition:** LS, ST, RS, LW, LF, CF, RF, RW, LAM, CAM, RAM, LM, LCM, CM, RCM, RM, LWB, LDM, CDM, RDM, RWB, LB, LCB, CB, RCB, RB, 
 - **Other:** Crossing, Finishing, Heading, Accuracy, ShortPassing, Volleys, Dribbling, Curve, FKAccuracy, LongPassing, BallControl, Acceleration, SprintSpeed, Agility, Reactions, Balance, ShotPower, Jumping, Stamina, Strength, LongShots, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Marking, StandingTackle, SlidingTackle, GKDiving, GKHandling, GKKicking, GKPositioning, GKReflexes, and Release Clause.

**Source:** https://www.kaggle.com/karangadiya/fifa19

Use the .toPandas() method to view the first few lines of the dataset so we know what we are working with.

In [6]:
fifa.limit(5).toPandas()

,_c0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96,33,28,26,6,11,15,14,8,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95,28,31,23,7,11,15,14,11,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94,27,24,33,9,9,15,15,11,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68,15,21,13,90,85,87,88,94,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88,68,58,51,15,13,5,10,13,€196.4M

Now print the schema of the dataset so we can see the data types of all the varaibles.

In [15]:
fifa.printSchema()

root
 |-- _c0: integer (nullable = true)
 |-- ID: integer (nullable = true)
 |-- Name: string (nullable = true)
 |-- Age: integer (nullable = true)
 |-- Photo: string (nullable = true)
 |-- Nationality: string (nullable = true)
 |-- Flag: string (nullable = true)
 |-- Overall: integer (nullable = true)
 |-- Potential: integer (nullable = true)
 |-- Club: string (nullable = true)
 |-- Club Logo: string (nullable = true)
 |-- Value: string (nullable = true)
 |-- Wage: string (nullable = true)
 |-- Special: integer (nullable = true)
 |-- Preferred Foot: string (nullable = true)
 |-- International Reputation: integer (nullable = true)
 |-- Weak Foot: integer (nullable = true)
 |-- Skill Moves: integer (nullable = true)
 |-- Work Rate: string (nullable = true)
 |-- Body Type: string (nullable = true)
 |-- Real Face: string (nullable = true)
 |-- Position: string (nullable = true)
 |-- Jersey Number: integer (nullable = true)
 |-- Joined: string (nullable = true)
 |-- Loaned From: string (nullable = true)
 |-- Contract Valid Until: string (nullable = true)
 |-- Height: string (nullable = true)
 |-- Weight: string (nullable = true)
 |-- LS: string (nullable = true)
 |-- ST: string (nullable = true)
 |-- RS: string (nullable = true)
 |-- LW: string (nullable = true)
 |-- LF: string (nullable = true)
 |-- CF: string (nullable = true)
 |-- RF: string (nullable = true)
 |-- RW: string (nullable = true)
 |-- LAM: string (nullable = true)
 |-- CAM: string (nullable = true)
 |-- RAM: string (nullable = true)
 |-- LM: string (nullable = true)
 |-- LCM: string (nullable = true)
 |-- CM: string (nullable = true)
 |-- RCM: string (nullable = true)
 |-- RM: string (nullable = true)
 |-- LWB: string (nullable = true)
 |-- LDM: string (nullable = true)
 |-- CDM: string (nullable = true)
 |-- RDM: string (nullable = true)
 |-- RWB: string (nullable = true)
 |-- LB: string (nullable = true)
 |-- LCB: string (nullable = true)
 |-- CB: string (nullable = true)
 |-- RCB: string (nullable = true)
 |-- RB: string (nullable = true)
 |-- Crossing: integer (nullable = true)
 |-- Finishing: integer (nullable = true)
 |-- HeadingAccuracy: integer (nullable = true)
 |-- ShortPassing: integer (nullable = true)
 |-- Volleys: integer (nullable = true)
 |-- Dribbling: integer (nullable = true)
 |-- Curve: integer (nullable = true)
 |-- FKAccuracy: integer (nullable = true)
 |-- LongPassing: integer (nullable = true)
 |-- BallControl: integer (nullable = true)
 |-- Acceleration: integer (nullable = true)
 |-- SprintSpeed: integer (nullable = true)
 |-- Agility: integer (nullable = true)
 |-- Reactions: integer (nullable = true)
 |-- Balance: integer (nullable = true)
 |-- ShotPower: integer (nullable = true)
 |-- Jumping: integer (nullable = true)
 |-- Stamina: integer (nullable = true)
 |-- Strength: integer (nullable = true)
 |-- LongShots: integer (nullable = true)
 |-- Aggression: integer (nullable = true)
 |-- Interceptions: integer (nullable = true)
 |-- Positioning: integer (nullable = true)
 |-- Vision: integer (nullable = true)
 |-- Penalties: integer (nullable = true)
 |-- Composure: integer (nullable = true)
 |-- Marking: integer (nullable = true)
 |-- StandingTackle: integer (nullable = true)
 |-- SlidingTackle: integer (nullable = true)
 |-- GKDiving: integer (nullable = true)
 |-- GKHandling: integer (nullable = true)
 |-- GKKicking: integer (nullable = true)
 |-- GKPositioning: integer (nullable = true)
 |-- GKReflexes: integer (nullable = true)
 |-- Release Clause: string (nullable = true)

## Now let's get started!

### First things first..... import the pyspark sql functions library

Since we know we will be using it a lot.

In [7]:
from pyspark.sql.functions import *

### 1. Select the Name and Position of each player in the dataframe

In [8]:
fifa.select(["Name","Position"]).show(5,False)

+-----------------+--------+
|Name             |Position|
+-----------------+--------+
|L. Messi         |RF      |
|Cristiano Ronaldo|ST      |
|Neymar Jr        |LW      |
|De Gea           |GK      |
|K. De Bruyne     |RCM     |
+-----------------+--------+
only showing top 5 rows

### 1.1 Display the same results from above sorted by the players names

In [20]:
fifa.select("Name","Position").orderBy(fifa.Name.asc()).toPandas()

                 Name Position
0            A. Abang       ST
1       A. Abdellaoui       LB
2        A. Abdennour       CB
3             A. Abdi       CM
4       A. Abdu Jaber       ST
...               ...      ...
18202       Óscar Gil       RB
18203    Óscar Pinchi       LM
18204     Óscar Plano       LM
18205  Óscar Valentín      CDM
18206   Óscar Whalley       GK

[18207 rows x 2 columns]

### 2. Select only the players who belong to a club begining with FC

In [10]:
#One way
fifa.select("Name","Club").filter(fifa.Club.startswith("FC")).toPandas()

                 Name                   Club
0            L. Messi           FC Barcelona
1           L. Suárez           FC Barcelona
2      R. Lewandowski      FC Bayern München
3       M. ter Stegen           FC Barcelona
4     Sergio Busquets           FC Barcelona
...               ...                    ...
1002    M. Humpenöder  FC Würzburger Kickers
1003     O. Dzonlagic                FC Thun
1004         O. Olsen         FC Midtjylland
1005       N. Stephan  FC Würzburger Kickers
1006   M. Finne Wørts        FC Nordsjælland

[1007 rows x 2 columns]

In [9]:
#Another way
fifa.select("Name","Club").where(fifa.Club.like("FC%")).show(5,False)

+---------------+-----------------+
|Name           |Club             |
+---------------+-----------------+
|L. Messi       |FC Barcelona     |
|L. Suárez      |FC Barcelona     |
|R. Lewandowski |FC Bayern München|
|M. ter Stegen  |FC Barcelona     |
|Sergio Busquets|FC Barcelona     |
+---------------+-----------------+
only showing top 5 rows

### 3. Who is the oldest player in the dataset and how old are they?

Display only the name and age of the oldest player.

In [12]:
#One way
fifa.orderBy(fifa.Age.desc()).select("Name","Age").show(1)

+--------+---+
|    Name|Age|
+--------+---+
|O. Pérez| 45|
+--------+---+
only showing top 1 row

In [13]:
#another way
fifa.select("Name","Age").sort(desc("Age")).show(1)

+--------+---+
|    Name|Age|
+--------+---+
|O. Pérez| 45|
+--------+---+
only showing top 1 row

### 4. Select only the following players from the dataframe:

 - L. Messi
 - Cristiano Ronaldo

In [32]:
#one way
fifa.filter(fifa.Name.isin(["L. Messi","Cristiano Ronaldo"])).toPandas()

,_c0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96,33,28,26,6,11,15,14,8,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95,28,31,23,7,11,15,14,11,€127.1M

In [14]:
fifa[fifa.Name.isin(["L. Messi","Cristiano Ronaldo"])].toPandas()

,_c0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96,33,28,26,6,11,15,14,8,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95,28,31,23,7,11,15,14,11,€127.1M

### 5. Can you select the first character from the Release Clause variable which indicates the currency used?

In [51]:
#without substring
fifa.select("Release Clause").limit(1).toPandas().loc[0].values[0][0]

'€'

In [15]:
#with substring1
fifa.select("Release Clause", fifa["Release Clause"].substr(1,1)).show(5)

#fifa["Relase Clause"]  is preferred form when a field has space.

+--------------+-------------------------------+
|Release Clause|substring(Release Clause, 1, 1)|
+--------------+-------------------------------+
|       €226.5M|                              €|
|       €127.1M|                              €|
|       €228.1M|                              €|
|       €138.6M|                              €|
|       €196.4M|                              €|
+--------------+-------------------------------+
only showing top 5 rows

### 6. Can you select only the players who are over the age of 40?

In [33]:
#one way
fifa.filter(fifa.Age>40).toPandas()

,_c0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,1120,156092,J. Villar,41,https://cdn.sofifa.org/players/4/19/156092.png,Paraguay,https://cdn.sofifa.org/flags/58.png,77,77,None,...,55,13,13,14,75,75,74,78,77,None
1,4228,3665,B. Nivet,41,https://cdn.sofifa.org/players/4/19/3665.png,France,https://cdn.sofifa.org/flags/18.png,71,71,ESTAC Troyes,...,82,58,56,43,11,7,8,14,7,None
2,4741,140029,O. Pérez,45,https://cdn.sofifa.org/players/4/19/140029.png,Mexico,https://cdn.sofifa.org/flags/83.png,71,71,Pachuca,...,62,23,12,11,70,64,65,73,74,€272K
3,7225,142998,C. Muñoz,41,https://cdn.sofifa.org/players/4/19/142998.png,Argentina,https://cdn.sofifa.org/flags/52.png,68,68,CD Universidad de Concepción,...,62,18,14,19,67,65,68,71,68,€84K
4,10545,140183,S. Narazaki,42,https://cdn.sofifa.org/players/4/19/140183.png,Japan,https://cdn.sofifa.org/flags/163.png,65,65,Nagoya Grampus,...,45,27,24,22,64,63,62,67,63,€50K
5,12192,208927,H. Sulaimani,41,https://cdn.sofifa.org/players/4/19/208927.png,Saudi Arabia,https://cdn.sofifa.org/flags/183.png,63,63,Ohod Club,...,67,62,66,63,15,8,15,14,13,None
6,15426,18745,M. Tyler,41,https://cdn.sofifa.org/players/4/19/18745.png,England,https://cdn.sofifa.org/flags/14.png,59,59,Peterborough United,...,57,24,16,17,61,54,54,63,55,€18K
7,17726,51963,T. Warner,44,https://cdn.sofifa.org/players/4/19/51963.png,Trinidad & Tobago,https://cdn.sofifa.org/flags/93.png,53,53,Accrington Stanley,...,46,19,15,14,48,56,56,60,44,None
8,18183,53748,K. Pilkington,44,https://cdn.sofifa.org/players/4/19/53748.png,England,https://cdn.sofifa.org/flags/14.png,48,48,Cambridge United,...,56,15,15,13,45,48,44,49,46,None

In [21]:
fifa.filter("Age>40").limit(4).toPandas()

,_c0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,1120,156092,J. Villar,41,https://cdn.sofifa.org/players/4/19/156092.png,Paraguay,https://cdn.sofifa.org/flags/58.png,77,77,None,...,55,13,13,14,75,75,74,78,77,None
1,4228,3665,B. Nivet,41,https://cdn.sofifa.org/players/4/19/3665.png,France,https://cdn.sofifa.org/flags/18.png,71,71,ESTAC Troyes,...,82,58,56,43,11,7,8,14,7,None
2,4741,140029,O. Pérez,45,https://cdn.sofifa.org/players/4/19/140029.png,Mexico,https://cdn.sofifa.org/flags/83.png,71,71,Pachuca,...,62,23,12,11,70,64,65,73,74,€272K
3,7225,142998,C. Muñoz,41,https://cdn.sofifa.org/players/4/19/142998.png,Argentina,https://cdn.sofifa.org/flags/52.png,68,68,CD Universidad de Concepción,...,62,18,14,19,67,65,68,71,68,€84K

### That's is for now... Great Job!